#!/bin/sh
printf "\n\n"
printf " ______         _ _________      __\n"
printf "|___  /        | |__   __\ \    / /\n"
printf "   / / ___   __| |  | |   \ \  / / \n"
printf "  / / / _ \ / _  |  | |    \ \/ /  \n"
printf " / /_| (_) | (_| |_ | |     \  /   \n"
printf "/_____\___/ \__,_(_)|_|      \/    \n"
printf "\n\n"